title: "Kiln"
description: "Kubernetes-native Bitcoin and Lightning infrastructure."
url: "https://kiln-fired.github.io"
baseurl: ""
author: "David Gordon"
github_org: "kiln-fired"
github_repo: "https://github.com/kiln-fired/kiln-operator"
permalink: /blog/:title/
markdown: kramdown
plugins:
  - jekyll-feed
